- name: Initialize the postal database.
  command: postal initialize

- name: Apply "/etc/systemd/system/postal.service" template to have postal managed by systemd.
  template:
    src: etc/systemd/system/postal.service
    dest: /etc/systemd/system/postal.service
    owner: root
    group: root
    mode: 0755

- name: Start postal.
  command: systemctl start postal
