- name: Initialize the postal database.
  command: postal initialize

- name: Apply "/etc/systemd/system/postal.service" template to have postal managed by systemd.
  template:
    src: etc/systemd/system/postal.service.j2
    dest: /etc/systemd/system/postal.service
    owner: root
    group: root
    mode: 0644

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: just force systemd to re-execute itself (2.8 and above)
  systemd:
    daemon_reexec: yes

- name: Start postal.
  systemd:
    name: postal
    state: started
    enabled: yes
