- name: Initialize the postal database.
  command: postal initialize

- name: Apply "/etc/rc.local" template to start postal at boot.
  template:
    src: etc/rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0644

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: just force systemd to re-execute itself (2.8 and above)
  systemd:
    daemon_reexec: yes

- name: Start postal.
  systemd:
    name: postal
    state: started
    enabled: yes
