---
- name: Add MariaDB key.
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xF1656F24C74CD1D8"
    state: present

- name: Add MariaDB repo.
  apt_repository:
    repo: 'deb [arch=amd64,arm64,ppc64el] http://ftp.nluug.nl/db/mariadb/repo/10.5/ubuntu bionic main'
    state: present
  register: mysql_new_install

- name: Ensure the MySQL Client is installed on the host.
  apt:
    state: latest
    name:
      - mariadb-client-10.5
      - python-mysqldb
    update_cache: yes

- name: Make sure pip3 is installed
  apt:
    name: python3-pip
    state: latest

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: latest