- name: restart postal
  systemd:
    name: postal
    state: restarted

- name: restart nginx
  command: nginx -t
  notify: validated nginx restart

- name: reload nginx
  command: nginx -t
  notify: validated nginx reload

- name: validated nginx restart
  systemd:
    name: nginx
    state: restarted

- name: validated nginx reload
  systemd:
    name: nginx
    state: reloaded